version: "3.8"
services:
  db:
    image: mysql
    container_name: miniproject_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: my_db_files
        target: /var/lib/mysql
  adminer:
    image: adminer
    container_name: miniproject_adminer_container
    restart: always
    ports:
      - 8080:8080
volumes:
  my_db_files: